version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=1234
      - MONGODB_DATABASE=dev
    volumes:
      - ./.db:/bitnami
