version: '2'

services:
  sweetdeals_dev:
    container_name: mongo_sweetdeals_dev
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=1234
      - MONGODB_DATABASE=dev
    volumes:
      - ./.db:/bitnami
  testdb:
    container_name: mongo_sweetdeals_test
    image: 'bitnami/mongodb:latest'
    ports:
      - "27016:27017"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=1234
      - MONGODB_DATABASE=test
    volumes:
      - ./.db_test:/bitnami
