apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: app
  name: app-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - image: vutrio/sweetdeals-image-demo
        name: app
        ports:
        - containerPort: 8000
          name: http-server
      imagePullSecrets:
        - name: regcred
