apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: bitnami/mongodb:latest
        name: mongo
        env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: MONGODB_USERNAME
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: MONGODB_PASSWORD
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: MONGODB_DATABASE
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
